### ISSUE TITLE
Distribution Request

### ISSUE THREAD

**Issue by archey** [routerkeygen/routerkeygenPC#12]
I am  a Developer for the ArchAssault project and we would like distribute this in our repo, however I was wondering if you push a new tag to as the 1.0.0 tag is fairly old from what I can tell.\

Thanks

**Comment by ruiaraujo** [comment]
I will try my best next week.

**Comment by archey** [comment]
Thanks much appreciated

**Comment by archey** [comment]
Any update on this>

**Comment by ruiaraujo** [comment]
Finally done it.
