### ISSUE TITLE
Error when building on mac

### ISSUE THREAD

**Issue by aldosolis** [routerkeygen/routerkeygenPC#14]
When running sh build_mac.sh I got the following error:

Build type set to 'Release'
-- Version: 1.1.0
Using Qt4
-- Translations: en;pt;nl;es
-- rpmbuild NOT found. RPM generation will not be available
-- dpkg-deb NOT found. deb generation will not be available
-- Configuring done
CMake Error at src/CMakeLists.txt:122 (add_executable):
  Cannot find source file:

    ../share/routerkeygen.entitlements

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

-- Build files have been written to: /Users/aldosolis/Projects/experimental/routerkeygenPC/mac
Could not create Makefiles

I realised that the entitlements file is missing, should I create it manually or something?

**Comment by pmoust** [comment]
Could not reproduce, just built routerkeygen on mac the othe day without any issue.

**Comment by ruiaraujo** [comment]
@aldosolis Can you try again  with the lastest master?

**Comment by pmoust** [comment]
@aldosolis if you trust 3rd party build, here is the .dmg https://www.dropbox.com/s/34ukwn9vjga3kc5/RouterKeygen_V1_1_0.dmg?dl=0
