### ISSUE TITLE
cmake minimum required

### ISSUE THREAD

**Issue by mamoit** [routerkeygen/routerkeygenPC#16]
The current minimum version is set to 2.8.11, but I was able to compile it using 2.8.9 just by commenting out the requirement.

**Comment by ruiaraujo** [comment]
That's a random requirement. Just happen to be the version I had at the time. I will change it later then.

**Comment by mamoit** [comment]
És rápido! :smile:

**Comment by ruiaraujo** [comment]
A true portuguese is efficient.

**Comment by mamoit** [comment]
:+1:
