### ISSUE TITLE
Vesrion 1.0.0 can't be build in Ubuntu Linux

### ISSUE THREAD

**Issue by GeorgeGkas** [routerkeygen/routerkeygenPC#20]
I downloaded the latest release of the program (v1.0.0) and I would like to run the `./build_linux.sh` file.
But then I get the following error in my terminal:

```
Build type set to 'Release'
-- Version: 1.0.0
CMake Warning (dev) at CMakeLists.txt:44 (PROJECT):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at /usr/share/cmake-3.0/Modules/FindQt4.cmake:1316 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:69 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/georgegk/Downloads/routerkeygenPC-1.0.0/linux/CMakeFiles/CMakeOutput.log".
Could not create Makefiles
```
What is the problem?

**Comment by pmoust** [comment]
QT 4 is missing from your system (as mentioned in the build log).

Try:
```
sudo apt-get install libqt4-dev libqt4-core libqt4-gui
```

And then build.

**Comment by GeorgeGkas** [comment]
Συγνώμη, τώρα κατάλαβα ότι είσαι Έλληνας. !! :)
Λοιπόν παρατηρώ ότι κάνατε πολύ καλή δουλειά. Αλλά μιας και είμαστε στην Ελλάδα γιατί δεν φτιάχνουμε κάτι που να ισχύεει εγχώρια. Πχ για τα δύκτια NetFaster γνωρίζουμε όλοι τι ισχύει. Επίσης στο πρόγραμμά σας έχετε ένα θέμα με τα δύκτια conn-x. Έχω 3 δίπλα μου και τα 3 χωρίς υποστήριξη. Πως και αυτό?
Υ.Γ
Δουλεύεω aircrack και έφτιαξα ένα προγραμματάκι δημιουργείας worldlist για Netfaster. Οι συνδαισμοί είναι 10.000 για ένα router με default κωδικό. Επίσης μπορεί κάποιο δύκτιο να είναι της Hol - neTFaster αλλά οο χρήστης να έχει αλλάξει το όνομα του δυκτίου. όλα αυτά θα μπορούσαμε να τα ελένξουμε άραγε?

**Comment by pmoust** [comment]
I am not a `routerkeygen` core maintainer. 
You 'll have way more chances in getting a response if you write in english.

To answer your question; You can rely on MAC address to gather some manufacturer info instead of just checking ESSID.
For most mainstream vendors the MAC address ranges are known.

**Comment by ruiaraujo** [comment]
@GeorgeGkas English only

**Comment by ruiaraujo** [comment]
@GeorgeGkas also if you're trying to build, you should grab the mast branch.
