### ISSUE TITLE
Avira warns for Something

### ISSUE THREAD

**Issue by Huskynarr** [routerkeygen/routerkeygenPC#21]
Sorry i don't know the Specific Message, but Avira shows message becuase Virus or Something.
Exists a way (Without Settings in Avira. :P ) to "Disable" this Message for this PRogramm?
Other User with not so much experience can get here Panic.

**Comment by ruiaraujo** [comment]
I am going to be a bit blunt but Avira is a piece of crap. The code is open source and there is no virus.
There's nothing I can do.
