### ISSUE TITLE
no wifi network scanning on linux

### ISSUE THREAD

**Issue by peterpt** [routerkeygen/routerkeygenPC#25]
Hi , i was able to compile the debian and install routerkeygen on my kali , however the tool does not get any wifi APS on scan .
Also windows version is doing the same .
It could be interesting a routine check in program to check wireless cards on the device and then user manually choose witch card to use .

**Comment by ruiaraujo** [comment]
Do you have Network Manager installed on Debian?

**Comment by ruiaraujo** [comment]
Also which Windows version do you use?

**Comment by peterpt** [comment]
I have kali Sana (2.0) installed , and i have other machine running XP .
in none of both the software runs .
the compilation on kali was good , i had to downgrade some libraries in order to compile with all dependencies .
kali sana is debian 8 .
And yes , network manager is installed .

**Comment by ruiaraujo** [comment]
Which libraries?

That probably means it is outdated.
I no longer have a linux machine which makes testing tricky.

**Comment by peterpt** [comment]
I did it a 2 weeks ago , i don't have many sure witch libraries were , but as far as i can remember it was related to Qt libraries and libssl .
Anyway , i use routerkeygen on my android device witch is working great .
And what about Windows version , do you have any idea why is not working either ?

**Comment by ruiaraujo** [comment]
Windows XP should be supported if fully updated, it requires SP3 at least.

**Comment by ruiaraujo** [comment]
Closed since I can't reproduce.
