### ISSUE TITLE
Doesn't build on Linux: Missing NetworkManager.h

### ISSUE THREAD

**Issue by rjsc** [routerkeygen/routerkeygenPC#3]
/src/wifi/NetworkManager.h and /src/wifi/NetworkManager.cpp are missing from the repository.

When I try to buikd, I get:

Building CXX object src/CMakeFiles/routerkeygen.dir/wifi/QWifiManager.cpp.o
In file included from /home/rjscosta/Desktop/routerkeygenPC-master/src/wifi/QWifiManager.cpp:31:0:
/home/user/Desktop/routerkeygenPC-master/src/wifi/QWifiManagerPrivateUnix.h:16:28: fatal error: NetworkManager.h: Ficheiro ou directoria inexistente
 #include <NetworkManager.h>
                            ^
compilation terminated.

**Comment by peterpt** [comment]
Interesting this topic , however i have to write my notes here .
Despite the fact that i had network-manager-dev installed i still had same issue .
My solution was to downgrade from version : 1.24.0-1   to 0.9.10.0-7+devuan1

I have a devuan OS , and that version can be found in jessie repo of devuan .

**Comment by edu-soto** [comment]
Hi, 
I got here while trying to install  `NetworkManager.h` header in Ubuntu.

I finally found a solution: nowadays `NetworkManager.h` file is part of the `libnm-dev` package. Hence a 
```sudo apt install libnm-dev```
should do the job.
