### ISSUE TITLE
Sitecom Algorithm

### ISSUE THREAD

**Issue by Mr-Pingu** [routerkeygen/routerkeygenPC#33]
Sitecom algorithm isn't fully working. Take a look here:https://bitbucket.org/dudux/sitecom/src/adee83c36b59e88e4d493023fe36585d94634923/sitecom.py?at=master&fileviewer=file-view-default 
that one does generate me good password from mac-adress while this one doesn't.

**Comment by RealEnder** [comment]
Can you provide sample BSSID (mac)?

**Comment by RealEnder** [comment]
Also, what version of RKG you're using? Sitecom works as in dudux's repo with latest master for me. This means you must compile from sources.

**Comment by ruiaraujo** [comment]
@RealEnder he probably means that there is a problem with the keygen selector.

**Comment by RealEnder** [comment]
That's why I asked for BSSID. Dudux's shows only these targets: "00:0c:f6","64:d1:a3", but maybe there are others.

**Comment by RealEnder** [comment]
Hi, I did some checks on my db for other valid BSSIDs and found none. Now waiting for @Mr-Pingu for more info on the issue.

**Comment by Mr-Pingu** [comment]
I totally missed this somehow. 
ESSID: Sitecom631178
BSSID: 00:0C:F6:63:11:78 
Password should be "DNISVCBAWHB0" according to the back of the router I had.

**Comment by ruiaraujo** [comment]
Ok, I have checked with the lasted sources and the correct password was generated.

Thansk @Mr-Pingu for getting back to us.
