### ISSUE TITLE
missing package during compilation

### ISSUE THREAD

**Issue by peterpt** [routerkeygen/routerkeygenPC#34]
[ 85%] Building CXX object src/CMakeFiles/routerkeygen.dir/RouterKeygen.cpp.o
[ 86%] Building CXX object src/CMakeFiles/routerkeygen.dir/WirelessMatcher.cpp.o
[ 88%] Building CXX object src/CMakeFiles/routerkeygen.dir/main.cpp.o
[ 89%] Building CXX object src/CMakeFiles/routerkeygen.dir/wifi/QScanResult.cpp.o
[ 91%] Building CXX object src/CMakeFiles/routerkeygen.dir/wifi/QWifiManagerPrivate.cpp.o
[ 92%] Building CXX object src/CMakeFiles/routerkeygen.dir/wifi/QWifiManager.cpp.o
In file included from /tools/wifi/routerkeygenPC/src/wifi/QWifiManager.cpp:31:0:
/tools/wifi/routerkeygenPC/src/wifi/QWifiManagerPrivateUnix.h:16:28: fatal error: NetworkManager.h: No such file or directory
compilation terminated.
make[2]: *** [src/CMakeFiles/routerkeygen.dir/wifi/QWifiManager.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/routerkeygen.dir/all] Error 2
make: *** [all] Error 2
Error while building

**Comment by peterpt** [comment]
Just forget it , i was installing QT5 from source and i totally forgot to check out requisites .
after installing network-manager-dev  problem disappeared .

Please close this issue .

**Comment by ruiaraujo** [comment]
Will do. Thanks.
