### ISSUE TITLE
UPC Networks

### ISSUE THREAD

**Issue by ipepe** [routerkeygen/routerkeygenPC#44]
Is UPC keygen good to add into routerkeygen? 
source: https://haxx.in/upc-wifi/

**Comment by RealEnder** [comment]
This is already implemented since 2016:
https://github.com/routerkeygen/routerkeygenPC/blob/master/src/algorithms/Upc07Keygen.cpp
https://github.com/routerkeygen/routerkeygenPC/blob/master/src/algorithms/Upc07UbeeKeygen.cpp
Just compile latest git HEAD.
